# Generated by Django 3.2.6 on 2021-08-26 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'TO_DO'), (1, 'ACTIVE'), (2, 'CONTROL'), (3, 'COMPLETED')], default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_finished', models.DateTimeField(null=True)),
                ('date_finished_planned', models.DateTimeField(default=main.models.return_date_time)),
                ('observers', models.ManyToManyField(db_index=True, related_name='observing_tasks', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.PositiveSmallIntegerField(choices=[(0, 'TO_DO'), (1, 'ACTIVE'), (2, 'CONTROL'), (3, 'COMPLETED')])),
                ('new_status', models.PositiveSmallIntegerField(choices=[(0, 'TO_DO'), (1, 'ACTIVE'), (2, 'CONTROL'), (3, 'COMPLETED')])),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='main.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_changed_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.task')),
                ('users', models.ManyToManyField(db_index=True, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
